### ISSUE TITLE
登录安卓闪退

### ISSUE THREAD

**Issue by cham1985** [reactnativecn/react-native-qq#12]
async _login() {
        try {
            var result = await QQAPI.login({
                scope: 'get_simple_userinfo'
            });
            console.log('登录成功===', result);
            ToastAndroid.show('登录成功==' + result, ToastAndroid.LONG);
        }
        catch (e) {
            console.log('登录失败===', e);
            ToastAndroid.show('登录失败==' + e, ToastAndroid.LONG);

        }
    }

调 登录函数 安卓真机 闪退

**Comment by tdzl2003** [comment]
能提供详细的日志吗？

**Comment by feisan** [comment]
这是我这里调用 QQAPI.login() 之后的日志

                                                                 com.facebook.react.bridge.NativeArgumentsParseException: RCTQQAPI.login got 4 arguments, expected 3
                                                                 at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:290)
                                                                 at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:187)
                                                                 at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:62)
                                                                 at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:432)
                                                                 at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(Native Method)
                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:193)
                                                                 at java.lang.Thread.run(Thread.java:818)

**Comment by kesyn** [comment]
+1

**Comment by caolu2017** [comment]
为什么我分享一点反应都没有，登录还有反应

**Comment by caolu2017** [comment]
为什么我分享一点反应都没有，登录还有反应

**Comment by caolu2017** [comment]
为什么我分享一点反应都没有，登录还有反应

**Comment by caolu2017** [comment]
为什么我分享一点反应都没有，登录还有反应

**Comment by caolu2017** [comment]
为什么我分享一点反应都没有，登录还有反应
