### ISSUE TITLE
登录回调问题

### ISSUE THREAD

**Issue by HengCC** [reactnativecn/react-native-qq#69]
为什么在模拟器中调用登录,在登录成功后是能够收到登录成功的回调的,但是放到真机测试上就会收不到回调. 连回调方法都没有被调用.
```
    QQAPI.login().then(data => {
      console.log(data)
    }).catch(e => {
     console.log('登陆失败:', e)
    })
```

真机上都不会被执行, 模拟器可以.

**Comment by mantou132** [comment]
我在安卓上也不能正确的调用回调;
不过是在 QQ 授权页面按 back button。

至于授权成功之后怎么样我还没有测试

**Comment by sunkaigoon** [comment]
我在授权界面进行授权有回调，但是按返回没有回调，用Android Studio看日志显示在按返回的时候报错了
10-31 09:14:26.565 1854-1872/? W/System.err: java.lang.SecurityException: No permission to write APN settings
10-31 09:14:26.565 1854-1872/? W/System.err:     at com.android.providers.telephony.TpProviderHw.checkPermission(TpProviderHw.java:1328)
10-31 09:14:26.565 1854-1872/? W/System.err:     at com.android.providers.telephony.TpProviderHw.query(TpProviderHw.java:578)
10-31 09:14:26.565 1854-1872/? W/System.err:     at com.android.providers.telephony.TpProviderHw.query(TpProviderHw.java:367)
10-31 09:14:26.565 1854-1872/? W/System.err:     at com.android.providers.telephony.TelephonyProvider.query(TelephonyProvider.java:67)
10-31 09:14:26.565 1854-1872/? W/System.err:     at android.content.ContentProvider.query(ContentProvider.java:1020)
10-31 09:14:26.565 1854-1872/? W/System.err:     at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
10-31 09:14:26.565 1854-1872/? W/System.err:     at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
10-31 09:14:26.565 1854-1872/? W/System.err:     at android.os.Binder.execTransact(Binder.java:565)
10-31 09:14:26.565 1854-1872/? E/DatabaseUtils: Writing exception to parcel
                                                java.lang.SecurityException: No permission to write APN settings
                                                    at com.android.providers.telephony.TpProviderHw.checkPermission(TpProviderHw.java:1328)
                                                    at com.android.providers.telephony.TpProviderHw.query(TpProviderHw.java:578)
                                                    at com.android.providers.telephony.TpProviderHw.query(TpProviderHw.java:367)
                                                    at com.android.providers.telephony.TelephonyProvider.query(TelephonyProvider.java:67)
                                                    at android.content.ContentProvider.query(ContentProvider.java:1020)
                                                    at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
                                                    at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
                                                    at android.os.Binder.execTransact(Binder.java:565)
10-31 09:14:26.566 16743-17233/? E/openSDK_LOG.APNUtil: getApn has exception: No permission to write APN settings
10-31 09:14:26.568 16743-17233/? E/openSDK_LOG.Util: getPackageInfo has exception: com.qzone
10-31 09:14:26.596 573-573/? E/Thermal-daemon: [battery] temp_new :25  temp_old :26
10-31 09:14:26.596 573-573/? E/Thermal-daemon: Report temperature: [battery] temp :25  report_threshold:1
10-31 09:14:26.597 573-573/? E/Thermal-daemon: [charger_ic] temp_new :29  temp_old :28
10-31 09:14:26.597 573-573/? E/Thermal-daemon: Report temperature: [charger_ic] temp :29  report_threshold:1
不知道是不是这个原因，正在排查
