### ISSUE TITLE
Calling View methods on another thread than the UI thread. at com.android.webview.chromium

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [reactnativecn/react-native-qq#90]
native:java.lang.IllegalStateException: Calling View methods on another thread than the UI thread. at com.android.webview.chromium.WebViewChromium.createThreadException(WebViewChromium.java:123) at com.android.webview.chromium.WebViewChromium.checkThread(WebViewChromium.java:125) at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:46) at android.webkit.WebView.<init>(WebView.java:651) at android.webkit.WebView.<init>(WebView.java:581) at android.webkit.WebView.<init>(WebView.java:564) at android.webkit.WebView.<init>(WebView.java:551) at android.webkit.WebView.<init>(WebView.java:541) at com.tencent.open.c.a.<init>(Unknown Source:0) at com.tencent.open.a.a(Unknown Source:34) at com.tencent.open.a.onCreate(Unknown Source:7) at android.app.Dialog.dispatchOnCreate(Dialog.java:528) at android.app.Dialog.show(Dialog.java:389) at com.tencent.connect.c.a.a(Unknown Source:693) at com.tencent.tauth.c.a(Unknown Source:18) at cn.reactnative.modules.qq.QQModule._shareToQQ(Unknown Source:223) at cn.reactnative.modules.qq.QQModule.shareToQQ(Unknown Source:1) at java.lang.reflect.Method.invoke(Native Method) at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:190) at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:23) at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) at android.os.Handler.handleCallback(Handler.java:808) at android.os.Handler.dispatchMessage(Handler.java:101) at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0) at android.os.Looper.loop(Looper.java:166) at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(Unknown Source:16) at java.lang.Thread.run(Thread.java:784)

**Comment by marcshilling** [comment]
@Darkhorse-Fraternity you ever figure this out?
